mlb_id_lookup = {
    'laa': 1,
    'angels': 1,
    'angels of anaheim': 1,
    'anaheim angels': 1,
    'los angeles angels of anaheim': 1,
    'los angeles angels': 1,
    'ari': 2,
    'diamondbacks': 2,
    'arizona diamondbacks': 2,
    'atl': 3,
    'braves': 3,
    'atlanta braves': 3,
    'bal': 4,
    'orioles': 4,
    'baltimore orioles': 4,
    'bos': 5,
    'red sox': 5,
    'boston red sox': 5,
    'chc': 6,
    'cubs': 6,
    'chicago cubs': 6,
    'chw': 7,
    'white sox': 7,
    'chicago white sox': 7,
    'cin': 8,
    'reds': 8,
    'cincinnati reds': 8,
    'cle': 9,
    'indians': 9,
    'guardians': 9,
    'cleveland indians': 9,
    'cleveland guardians': 9,
    'col': 10,
    'rockies': 10,
    'colorado rockies': 10,
    'det': 11,
    'tigers': 11,
    'detroit tigers': 11,
    'mia': 12,
    'marlins': 12,
    'florida marlins': 12,
    'miami marlins': 12,
    'hou': 13,
    'astros': 13,
    'houston astros': 13,
    'kc': 14,
    'royals': 14,
    'kansas city royals': 14,
    'lad': 15,
    'dodgers': 15,
    'los angeles dodgers': 15,
    'mil': 16,
    'brewers': 16,
    'milwaukee brewers': 16,
    'min': 17,
    'twins': 17,
    'minnesota twins': 17,
    'expos': 18,
    'montreal expos': 18,
    'nym': 19,
    'mets': 19,
    'new york mets': 19,
    'nyy': 20,
    'yankees': 20,
    'new york yankees': 20,
    'oak': 21,
    'athletics': 21,
    'oakland athletics': 21,
    'phi': 22,
    'phillies': 22,
    'philadelphia phillies': 22,
    'pit': 23,
    'pirates': 23,
    'pittsburgh pirates': 23,
    'sd': 24,
    'padres': 24,
    'san diego padres': 24,
    'sea': 25,
    'mariners': 25,
    'seattle mariners': 25,
    'sf': 26,
    'giants': 26,
    'san francisco giants': 26,
    'stl': 27,
    'cardinals': 27,
    'st. louis cardinals': 27,
    'tb': 28,
    'devil rays': 28,
    'rays': 28,
    'tampa bay rays': 28,
    'tampa bay devil rays': 28,
    'tex': 29,
    'rangers': 29,
    'texas rangers': 29,
    'tor': 30,
    'blue jays': 30,
    'toronto blue jays': 30,
    'wsh': 31,
    'nationals': 31,
    'washington nationals': 31,
}

class TeamNormalizer():
    def get(self, team: str) -> int:
        q = team.lower()
        if q == 'tot':
            return -1

        if not q in mlb_id_lookup:
            raise KeyError(f'"{team}" is not supported.')

        return mlb_id_lookup[q]
