mlb-team-stats:
	python ./tasks/mlb/team_season_stats.py 2020 2021 2022

mlb-player-stats:
	python ./tasks/mlb/player_season_stats.py correca01

prefect:
	prefect orion start

mypy:
	mypy ./ --ignore-missing-imports